design_task:
  description: >
    Take the high level requirements described here and prepare an architecture design for the engineering team;
    the architecture should have a high level section describing how the modules work together to solve the
    requirements. The architecture should create a list of modules needed to complete the project. The architecture
    should include a section for each module in the high level design. Each module should have a name that gets
    handed to the engineering lead for delegation. Each module should have a name and be implemented by one class
    with the same name as the module name.
    Here are the requirements: {requirements}
    IMPORTANT: Only output the hgih level architecture in markdown format, starting with the high level design of
    how the modules work together, then include one section for each module that includes the module name,
    the class name (that is the same as the module name), the module interface methods and an example of the
    module being used in code.
  expected_output: >
    A high level architecture design document for the engineeringn lead that includes a high level design and
    a section with each module. It should specify the list of module names that can be used by the engineering 
    lead to delegate modules to engineering team members for implementation.
  agent: software_architect
  output_file: output/architecture_design.md
